package WebAutomation;// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class RedmineloginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {

    System.setProperty("webdriver.gecko.driver", "/home/joao/Documents/geckodriver");

    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void redminelogin() {
    driver.get("http://demo.redmine.org/");
    driver.manage().window().setSize(new Dimension(1853, 1053));
    driver.findElement(By.linkText("Sign in")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("jmnmv99");
    driver.findElement(By.id("password")).sendKeys("2001Internetcod!");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.linkText("Sign out")).click();

    assertThat(driver.findElement(By.linkText("Sign in")).getText(), is("Sign in"));
  }
}
